// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/category"
	"github.com/matheusgosk8/book-me-server/ent/order"
	"github.com/matheusgosk8/book-me-server/ent/proposal"
	"github.com/matheusgosk8/book-me-server/ent/review"
	"github.com/matheusgosk8/book-me-server/ent/transaction"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetDescription sets the "description" field.
func (_c *OrderCreate) SetDescription(v string) *OrderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v string) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *string) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *OrderCreate) SetLatitude(v float64) *OrderCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *OrderCreate) SetLongitude(v float64) *OrderCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *OrderCreate) SetScheduledAt(v time.Time) *OrderCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableScheduledAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderCreate) SetID(v uuid.UUID) *OrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrderCreate) SetNillableID(v *uuid.UUID) *OrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClientID sets the "client" edge to the User entity by ID.
func (_c *OrderCreate) SetClientID(id uuid.UUID) *OrderCreate {
	_c.mutation.SetClientID(id)
	return _c
}

// SetClient sets the "client" edge to the User entity.
func (_c *OrderCreate) SetClient(v *User) *OrderCreate {
	return _c.SetClientID(v.ID)
}

// SetProviderID sets the "provider" edge to the User entity by ID.
func (_c *OrderCreate) SetProviderID(id uuid.UUID) *OrderCreate {
	_c.mutation.SetProviderID(id)
	return _c
}

// SetNillableProviderID sets the "provider" edge to the User entity by ID if the given value is not nil.
func (_c *OrderCreate) SetNillableProviderID(id *uuid.UUID) *OrderCreate {
	if id != nil {
		_c = _c.SetProviderID(*id)
	}
	return _c
}

// SetProvider sets the "provider" edge to the User entity.
func (_c *OrderCreate) SetProvider(v *User) *OrderCreate {
	return _c.SetProviderID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *OrderCreate) SetCategoryID(id uuid.UUID) *OrderCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *OrderCreate) SetCategory(v *Category) *OrderCreate {
	return _c.SetCategoryID(v.ID)
}

// AddProposalIDs adds the "proposals" edge to the Proposal entity by IDs.
func (_c *OrderCreate) AddProposalIDs(ids ...uuid.UUID) *OrderCreate {
	_c.mutation.AddProposalIDs(ids...)
	return _c
}

// AddProposals adds the "proposals" edges to the Proposal entity.
func (_c *OrderCreate) AddProposals(v ...*Proposal) *OrderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProposalIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (_c *OrderCreate) AddReviewIDs(ids ...uuid.UUID) *OrderCreate {
	_c.mutation.AddReviewIDs(ids...)
	return _c
}

// AddReviews adds the "reviews" edges to the Review entity.
func (_c *OrderCreate) AddReviews(v ...*Review) *OrderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *OrderCreate) AddTransactionIDs(ids ...uuid.UUID) *OrderCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *OrderCreate) AddTransactions(v ...*Transaction) *OrderCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := order.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := order.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Order.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Order.latitude"`)}
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "Order.longitude"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required edge "Order.client"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "Order.category"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(order.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(order.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(order.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(order.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ClientTable,
			Columns: []string{order.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_orders_created = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProviderTable,
			Columns: []string{order.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_orders_fulfilled = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.CategoryTable,
			Columns: []string{order.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.category_orders = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProposalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ProposalsTable,
			Columns: []string{order.ProposalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proposal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ReviewsTable,
			Columns: []string{order.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.TransactionsTable,
			Columns: []string{order.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
