// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/providerprofile"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// ProviderProfile is the model entity for the ProviderProfile schema.
type ProviderProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Bio holds the value of the "bio" field.
	Bio string `json:"bio,omitempty"`
	// RatingAvg holds the value of the "rating_avg" field.
	RatingAvg float64 `json:"rating_avg,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderProfileQuery when eager-loading is set.
	Edges                 ProviderProfileEdges `json:"edges"`
	user_provider_profile *uuid.UUID
	selectValues          sql.SelectValues
}

// ProviderProfileEdges holds the relations/edges for other nodes in the graph.
type ProviderProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProviderProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerprofile.FieldIsActive:
			values[i] = new(sql.NullBool)
		case providerprofile.FieldRatingAvg:
			values[i] = new(sql.NullFloat64)
		case providerprofile.FieldBio:
			values[i] = new(sql.NullString)
		case providerprofile.FieldID:
			values[i] = new(uuid.UUID)
		case providerprofile.ForeignKeys[0]: // user_provider_profile
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderProfile fields.
func (_m *ProviderProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerprofile.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case providerprofile.FieldBio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bio", values[i])
			} else if value.Valid {
				_m.Bio = value.String
			}
		case providerprofile.FieldRatingAvg:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating_avg", values[i])
			} else if value.Valid {
				_m.RatingAvg = value.Float64
			}
		case providerprofile.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case providerprofile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_provider_profile", values[i])
			} else if value.Valid {
				_m.user_provider_profile = new(uuid.UUID)
				*_m.user_provider_profile = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderProfile.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ProviderProfile entity.
func (_m *ProviderProfile) QueryUser() *UserQuery {
	return NewProviderProfileClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ProviderProfile.
// Note that you need to call ProviderProfile.Unwrap() before calling this method if this ProviderProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderProfile) Update() *ProviderProfileUpdateOne {
	return NewProviderProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderProfile) Unwrap() *ProviderProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderProfile) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bio=")
	builder.WriteString(_m.Bio)
	builder.WriteString(", ")
	builder.WriteString("rating_avg=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatingAvg))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderProfiles is a parsable slice of ProviderProfile.
type ProviderProfiles []*ProviderProfile
