// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/order"
	"github.com/matheusgosk8/book-me-server/ent/predicate"
	"github.com/matheusgosk8/book-me-server/ent/review"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdate) SetRating(v int) *ReviewUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableRating(v *int) *ReviewUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdate) AddRating(v int) *ReviewUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewUpdate) SetComment(v string) *ReviewUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableComment(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *ReviewUpdate) ClearComment() *ReviewUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewUpdate) SetCreatedAt(v time.Time) *ReviewUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableCreatedAt(v *time.Time) *ReviewUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *ReviewUpdate) SetOrderID(id uuid.UUID) *ReviewUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *ReviewUpdate) SetOrder(v *Order) *ReviewUpdate {
	return _u.SetOrderID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *ReviewUpdate) SetAuthorID(id uuid.UUID) *ReviewUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *ReviewUpdate) SetAuthor(v *User) *ReviewUpdate {
	return _u.SetAuthorID(v.ID)
}

// SetSubjectID sets the "subject" edge to the User entity by ID.
func (_u *ReviewUpdate) SetSubjectID(id uuid.UUID) *ReviewUpdate {
	_u.mutation.SetSubjectID(id)
	return _u
}

// SetSubject sets the "subject" edge to the User entity.
func (_u *ReviewUpdate) SetSubject(v *User) *ReviewUpdate {
	return _u.SetSubjectID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdate) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *ReviewUpdate) ClearOrder() *ReviewUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *ReviewUpdate) ClearAuthor() *ReviewUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearSubject clears the "subject" edge to the User entity.
func (_u *ReviewUpdate) ClearSubject() *ReviewUpdate {
	_u.mutation.ClearSubject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewUpdate) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.order"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.author"`)
	}
	if _u.mutation.SubjectCleared() && len(_u.mutation.SubjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.subject"`)
	}
	return nil
}

func (_u *ReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(review.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OrderTable,
			Columns: []string{review.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OrderTable,
			Columns: []string{review.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AuthorTable,
			Columns: []string{review.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AuthorTable,
			Columns: []string{review.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.SubjectTable,
			Columns: []string{review.SubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.SubjectTable,
			Columns: []string{review.SubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetRating sets the "rating" field.
func (_u *ReviewUpdateOne) SetRating(v int) *ReviewUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableRating(v *int) *ReviewUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ReviewUpdateOne) AddRating(v int) *ReviewUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ReviewUpdateOne) SetComment(v string) *ReviewUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableComment(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *ReviewUpdateOne) ClearComment() *ReviewUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReviewUpdateOne) SetCreatedAt(v time.Time) *ReviewUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableCreatedAt(v *time.Time) *ReviewUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *ReviewUpdateOne) SetOrderID(id uuid.UUID) *ReviewUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *ReviewUpdateOne) SetOrder(v *Order) *ReviewUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *ReviewUpdateOne) SetAuthorID(id uuid.UUID) *ReviewUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *ReviewUpdateOne) SetAuthor(v *User) *ReviewUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// SetSubjectID sets the "subject" edge to the User entity by ID.
func (_u *ReviewUpdateOne) SetSubjectID(id uuid.UUID) *ReviewUpdateOne {
	_u.mutation.SetSubjectID(id)
	return _u
}

// SetSubject sets the "subject" edge to the User entity.
func (_u *ReviewUpdateOne) SetSubject(v *User) *ReviewUpdateOne {
	return _u.SetSubjectID(v.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdateOne) Mutation() *ReviewMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *ReviewUpdateOne) ClearOrder() *ReviewUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *ReviewUpdateOne) ClearAuthor() *ReviewUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearSubject clears the "subject" edge to the User entity.
func (_u *ReviewUpdateOne) ClearSubject() *ReviewUpdateOne {
	_u.mutation.ClearSubject()
	return _u
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Review entity.
func (_u *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReviewUpdateOne) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.order"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.author"`)
	}
	if _u.mutation.SubjectCleared() && len(_u.mutation.SubjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Review.subject"`)
	}
	return nil
}

func (_u *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(review.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(review.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OrderTable,
			Columns: []string{review.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.OrderTable,
			Columns: []string{review.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AuthorTable,
			Columns: []string{review.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.AuthorTable,
			Columns: []string{review.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.SubjectTable,
			Columns: []string{review.SubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.SubjectTable,
			Columns: []string{review.SubjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Review{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
