// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/address"
	"github.com/matheusgosk8/book-me-server/ent/category"
	"github.com/matheusgosk8/book-me-server/ent/order"
	"github.com/matheusgosk8/book-me-server/ent/proposal"
	"github.com/matheusgosk8/book-me-server/ent/providerprofile"
	"github.com/matheusgosk8/book-me-server/ent/review"
	"github.com/matheusgosk8/book-me-server/ent/schema"
	"github.com/matheusgosk8/book-me-server/ent/service"
	"github.com/matheusgosk8/book-me-server/ent/session"
	"github.com/matheusgosk8/book-me-server/ent/transaction"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescIsPrimary is the schema descriptor for is_primary field.
	addressDescIsPrimary := addressFields[9].Descriptor()
	// address.DefaultIsPrimary holds the default value on creation for the is_primary field.
	address.DefaultIsPrimary = addressDescIsPrimary.Default.(bool)
	// addressDescCreatedAt is the schema descriptor for created_at field.
	addressDescCreatedAt := addressFields[10].Descriptor()
	// address.DefaultCreatedAt holds the default value on creation for the created_at field.
	address.DefaultCreatedAt = addressDescCreatedAt.Default.(func() time.Time)
	// addressDescUpdatedAt is the schema descriptor for updated_at field.
	addressDescUpdatedAt := addressFields[11].Descriptor()
	// address.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	address.DefaultUpdatedAt = addressDescUpdatedAt.Default.(func() time.Time)
	// address.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	address.UpdateDefaultUpdatedAt = addressDescUpdatedAt.UpdateDefault.(func() time.Time)
	// addressDescID is the schema descriptor for id field.
	addressDescID := addressFields[0].Descriptor()
	// address.DefaultID holds the default value on creation for the id field.
	address.DefaultID = addressDescID.Default.(func() uuid.UUID)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescIsActive is the schema descriptor for is_active field.
	categoryDescIsActive := categoryFields[2].Descriptor()
	// category.DefaultIsActive holds the default value on creation for the is_active field.
	category.DefaultIsActive = categoryDescIsActive.Default.(bool)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.DefaultID holds the default value on creation for the id field.
	category.DefaultID = categoryDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[2].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[6].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	proposalFields := schema.Proposal{}.Fields()
	_ = proposalFields
	// proposalDescStatus is the schema descriptor for status field.
	proposalDescStatus := proposalFields[3].Descriptor()
	// proposal.DefaultStatus holds the default value on creation for the status field.
	proposal.DefaultStatus = proposalDescStatus.Default.(string)
	// proposalDescID is the schema descriptor for id field.
	proposalDescID := proposalFields[0].Descriptor()
	// proposal.DefaultID holds the default value on creation for the id field.
	proposal.DefaultID = proposalDescID.Default.(func() uuid.UUID)
	providerprofileFields := schema.ProviderProfile{}.Fields()
	_ = providerprofileFields
	// providerprofileDescRatingAvg is the schema descriptor for rating_avg field.
	providerprofileDescRatingAvg := providerprofileFields[2].Descriptor()
	// providerprofile.DefaultRatingAvg holds the default value on creation for the rating_avg field.
	providerprofile.DefaultRatingAvg = providerprofileDescRatingAvg.Default.(float64)
	// providerprofileDescIsActive is the schema descriptor for is_active field.
	providerprofileDescIsActive := providerprofileFields[3].Descriptor()
	// providerprofile.DefaultIsActive holds the default value on creation for the is_active field.
	providerprofile.DefaultIsActive = providerprofileDescIsActive.Default.(bool)
	// providerprofileDescID is the schema descriptor for id field.
	providerprofileDescID := providerprofileFields[0].Descriptor()
	// providerprofile.DefaultID holds the default value on creation for the id field.
	providerprofile.DefaultID = providerprofileDescID.Default.(func() uuid.UUID)
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescCreatedAt is the schema descriptor for created_at field.
	reviewDescCreatedAt := reviewFields[3].Descriptor()
	// review.DefaultCreatedAt holds the default value on creation for the created_at field.
	review.DefaultCreatedAt = reviewDescCreatedAt.Default.(func() time.Time)
	// reviewDescID is the schema descriptor for id field.
	reviewDescID := reviewFields[0].Descriptor()
	// review.DefaultID holds the default value on creation for the id field.
	review.DefaultID = reviewDescID.Default.(func() uuid.UUID)
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescTitle is the schema descriptor for title field.
	serviceDescTitle := serviceFields[1].Descriptor()
	// service.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	service.TitleValidator = serviceDescTitle.Validators[0].(func(string) error)
	// serviceDescPriceBase is the schema descriptor for price_base field.
	serviceDescPriceBase := serviceFields[3].Descriptor()
	// service.PriceBaseValidator is a validator for the "price_base" field. It is called by the builders before save.
	service.PriceBaseValidator = serviceDescPriceBase.Validators[0].(func(float64) error)
	// serviceDescDurationMinutes is the schema descriptor for duration_minutes field.
	serviceDescDurationMinutes := serviceFields[5].Descriptor()
	// service.DurationMinutesValidator is a validator for the "duration_minutes" field. It is called by the builders before save.
	service.DurationMinutesValidator = serviceDescDurationMinutes.Validators[0].(func(int) error)
	// serviceDescIsActive is the schema descriptor for is_active field.
	serviceDescIsActive := serviceFields[6].Descriptor()
	// service.DefaultIsActive holds the default value on creation for the is_active field.
	service.DefaultIsActive = serviceDescIsActive.Default.(bool)
	// serviceDescCreatedAt is the schema descriptor for created_at field.
	serviceDescCreatedAt := serviceFields[7].Descriptor()
	// service.DefaultCreatedAt holds the default value on creation for the created_at field.
	service.DefaultCreatedAt = serviceDescCreatedAt.Default.(func() time.Time)
	// serviceDescIsInPlace is the schema descriptor for is_in_place field.
	serviceDescIsInPlace := serviceFields[8].Descriptor()
	// service.DefaultIsInPlace holds the default value on creation for the is_in_place field.
	service.DefaultIsInPlace = serviceDescIsInPlace.Default.(bool)
	// serviceDescID is the schema descriptor for id field.
	serviceDescID := serviceFields[0].Descriptor()
	// service.DefaultID holds the default value on creation for the id field.
	service.DefaultID = serviceDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescLastLoginAt is the schema descriptor for last_login_at field.
	sessionDescLastLoginAt := sessionFields[2].Descriptor()
	// session.DefaultLastLoginAt holds the default value on creation for the last_login_at field.
	session.DefaultLastLoginAt = sessionDescLastLoginAt.Default.(func() time.Time)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[4].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[14].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[15].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
