// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/category"
	"github.com/matheusgosk8/book-me-server/ent/service"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// Service is the model entity for the Service schema.
type Service struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PriceBase holds the value of the "price_base" field.
	PriceBase float64 `json:"price_base,omitempty"`
	// fixed: valor único | hourly: valor multiplicado pelas horas
	PriceType service.PriceType `json:"price_type,omitempty"`
	// Duração média em minutos do serviço
	DurationMinutes int `json:"duration_minutes,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// IsInPlace holds the value of the "is_in_place" field.
	IsInPlace bool `json:"is_in_place,omitempty"`
	// AddressID holds the value of the "address_id" field.
	AddressID *uuid.UUID `json:"address_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ServiceQuery when eager-loading is set.
	Edges             ServiceEdges `json:"edges"`
	category_services *uuid.UUID
	user_services     *uuid.UUID
	selectValues      sql.SelectValues
}

// ServiceEdges holds the relations/edges for other nodes in the graph.
type ServiceEdges struct {
	// Provider holds the value of the provider edge.
	Provider *User `json:"provider,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServiceEdges) ProviderOrErr() (*User, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ServiceEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Service) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case service.FieldAddressID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case service.FieldIsActive, service.FieldIsInPlace:
			values[i] = new(sql.NullBool)
		case service.FieldPriceBase:
			values[i] = new(sql.NullFloat64)
		case service.FieldDurationMinutes:
			values[i] = new(sql.NullInt64)
		case service.FieldTitle, service.FieldDescription, service.FieldPriceType:
			values[i] = new(sql.NullString)
		case service.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case service.FieldID:
			values[i] = new(uuid.UUID)
		case service.ForeignKeys[0]: // category_services
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case service.ForeignKeys[1]: // user_services
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Service fields.
func (_m *Service) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case service.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case service.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case service.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case service.FieldPriceBase:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price_base", values[i])
			} else if value.Valid {
				_m.PriceBase = value.Float64
			}
		case service.FieldPriceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_type", values[i])
			} else if value.Valid {
				_m.PriceType = service.PriceType(value.String)
			}
		case service.FieldDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_minutes", values[i])
			} else if value.Valid {
				_m.DurationMinutes = int(value.Int64)
			}
		case service.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case service.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case service.FieldIsInPlace:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_in_place", values[i])
			} else if value.Valid {
				_m.IsInPlace = value.Bool
			}
		case service.FieldAddressID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field address_id", values[i])
			} else if value.Valid {
				_m.AddressID = new(uuid.UUID)
				*_m.AddressID = *value.S.(*uuid.UUID)
			}
		case service.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field category_services", values[i])
			} else if value.Valid {
				_m.category_services = new(uuid.UUID)
				*_m.category_services = *value.S.(*uuid.UUID)
			}
		case service.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_services", values[i])
			} else if value.Valid {
				_m.user_services = new(uuid.UUID)
				*_m.user_services = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Service.
// This includes values selected through modifiers, order, etc.
func (_m *Service) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the Service entity.
func (_m *Service) QueryProvider() *UserQuery {
	return NewServiceClient(_m.config).QueryProvider(_m)
}

// QueryCategory queries the "category" edge of the Service entity.
func (_m *Service) QueryCategory() *CategoryQuery {
	return NewServiceClient(_m.config).QueryCategory(_m)
}

// Update returns a builder for updating this Service.
// Note that you need to call Service.Unwrap() before calling this method if this Service
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Service) Update() *ServiceUpdateOne {
	return NewServiceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Service entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Service) Unwrap() *Service {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Service is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Service) String() string {
	var builder strings.Builder
	builder.WriteString("Service(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("price_base=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceBase))
	builder.WriteString(", ")
	builder.WriteString("price_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceType))
	builder.WriteString(", ")
	builder.WriteString("duration_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMinutes))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_in_place=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsInPlace))
	builder.WriteString(", ")
	if v := _m.AddressID; v != nil {
		builder.WriteString("address_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Services is a parsable slice of Service.
type Services []*Service
