// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/category"
	"github.com/matheusgosk8/book-me-server/ent/predicate"
	"github.com/matheusgosk8/book-me-server/ent/service"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// ServiceUpdate is the builder for updating Service entities.
type ServiceUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceMutation
}

// Where appends a list predicates to the ServiceUpdate builder.
func (_u *ServiceUpdate) Where(ps ...predicate.Service) *ServiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ServiceUpdate) SetTitle(v string) *ServiceUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableTitle(v *string) *ServiceUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceUpdate) SetDescription(v string) *ServiceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableDescription(v *string) *ServiceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceUpdate) ClearDescription() *ServiceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriceBase sets the "price_base" field.
func (_u *ServiceUpdate) SetPriceBase(v float64) *ServiceUpdate {
	_u.mutation.ResetPriceBase()
	_u.mutation.SetPriceBase(v)
	return _u
}

// SetNillablePriceBase sets the "price_base" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillablePriceBase(v *float64) *ServiceUpdate {
	if v != nil {
		_u.SetPriceBase(*v)
	}
	return _u
}

// AddPriceBase adds value to the "price_base" field.
func (_u *ServiceUpdate) AddPriceBase(v float64) *ServiceUpdate {
	_u.mutation.AddPriceBase(v)
	return _u
}

// SetPriceType sets the "price_type" field.
func (_u *ServiceUpdate) SetPriceType(v service.PriceType) *ServiceUpdate {
	_u.mutation.SetPriceType(v)
	return _u
}

// SetNillablePriceType sets the "price_type" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillablePriceType(v *service.PriceType) *ServiceUpdate {
	if v != nil {
		_u.SetPriceType(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *ServiceUpdate) SetDurationMinutes(v int) *ServiceUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableDurationMinutes(v *int) *ServiceUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *ServiceUpdate) AddDurationMinutes(v int) *ServiceUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceUpdate) SetIsActive(v bool) *ServiceUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableIsActive(v *bool) *ServiceUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetProviderID sets the "provider" edge to the User entity by ID.
func (_u *ServiceUpdate) SetProviderID(id uuid.UUID) *ServiceUpdate {
	_u.mutation.SetProviderID(id)
	return _u
}

// SetProvider sets the "provider" edge to the User entity.
func (_u *ServiceUpdate) SetProvider(v *User) *ServiceUpdate {
	return _u.SetProviderID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *ServiceUpdate) SetCategoryID(id uuid.UUID) *ServiceUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *ServiceUpdate) SetCategory(v *Category) *ServiceUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the ServiceMutation object of the builder.
func (_u *ServiceUpdate) Mutation() *ServiceMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the User entity.
func (_u *ServiceUpdate) ClearProvider() *ServiceUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *ServiceUpdate) ClearCategory() *ServiceUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := service.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Service.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceBase(); ok {
		if err := service.PriceBaseValidator(v); err != nil {
			return &ValidationError{Name: "price_base", err: fmt.Errorf(`ent: validator failed for field "Service.price_base": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceType(); ok {
		if err := service.PriceTypeValidator(v); err != nil {
			return &ValidationError{Name: "price_type", err: fmt.Errorf(`ent: validator failed for field "Service.price_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := service.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "Service.duration_minutes": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Service.provider"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Service.category"`)
	}
	return nil
}

func (_u *ServiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(service.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(service.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PriceBase(); ok {
		_spec.SetField(service.FieldPriceBase, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceBase(); ok {
		_spec.AddField(service.FieldPriceBase, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceType(); ok {
		_spec.SetField(service.FieldPriceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(service.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(service.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(service.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.ProviderTable,
			Columns: []string{service.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.ProviderTable,
			Columns: []string{service.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.CategoryTable,
			Columns: []string{service.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.CategoryTable,
			Columns: []string{service.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceUpdateOne is the builder for updating a single Service entity.
type ServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceMutation
}

// SetTitle sets the "title" field.
func (_u *ServiceUpdateOne) SetTitle(v string) *ServiceUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableTitle(v *string) *ServiceUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceUpdateOne) SetDescription(v string) *ServiceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableDescription(v *string) *ServiceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceUpdateOne) ClearDescription() *ServiceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPriceBase sets the "price_base" field.
func (_u *ServiceUpdateOne) SetPriceBase(v float64) *ServiceUpdateOne {
	_u.mutation.ResetPriceBase()
	_u.mutation.SetPriceBase(v)
	return _u
}

// SetNillablePriceBase sets the "price_base" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillablePriceBase(v *float64) *ServiceUpdateOne {
	if v != nil {
		_u.SetPriceBase(*v)
	}
	return _u
}

// AddPriceBase adds value to the "price_base" field.
func (_u *ServiceUpdateOne) AddPriceBase(v float64) *ServiceUpdateOne {
	_u.mutation.AddPriceBase(v)
	return _u
}

// SetPriceType sets the "price_type" field.
func (_u *ServiceUpdateOne) SetPriceType(v service.PriceType) *ServiceUpdateOne {
	_u.mutation.SetPriceType(v)
	return _u
}

// SetNillablePriceType sets the "price_type" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillablePriceType(v *service.PriceType) *ServiceUpdateOne {
	if v != nil {
		_u.SetPriceType(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *ServiceUpdateOne) SetDurationMinutes(v int) *ServiceUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableDurationMinutes(v *int) *ServiceUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *ServiceUpdateOne) AddDurationMinutes(v int) *ServiceUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceUpdateOne) SetIsActive(v bool) *ServiceUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableIsActive(v *bool) *ServiceUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetProviderID sets the "provider" edge to the User entity by ID.
func (_u *ServiceUpdateOne) SetProviderID(id uuid.UUID) *ServiceUpdateOne {
	_u.mutation.SetProviderID(id)
	return _u
}

// SetProvider sets the "provider" edge to the User entity.
func (_u *ServiceUpdateOne) SetProvider(v *User) *ServiceUpdateOne {
	return _u.SetProviderID(v.ID)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *ServiceUpdateOne) SetCategoryID(id uuid.UUID) *ServiceUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *ServiceUpdateOne) SetCategory(v *Category) *ServiceUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the ServiceMutation object of the builder.
func (_u *ServiceUpdateOne) Mutation() *ServiceMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the User entity.
func (_u *ServiceUpdateOne) ClearProvider() *ServiceUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *ServiceUpdateOne) ClearCategory() *ServiceUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the ServiceUpdate builder.
func (_u *ServiceUpdateOne) Where(ps ...predicate.Service) *ServiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceUpdateOne) Select(field string, fields ...string) *ServiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Service entity.
func (_u *ServiceUpdateOne) Save(ctx context.Context) (*Service, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceUpdateOne) SaveX(ctx context.Context) *Service {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := service.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Service.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceBase(); ok {
		if err := service.PriceBaseValidator(v); err != nil {
			return &ValidationError{Name: "price_base", err: fmt.Errorf(`ent: validator failed for field "Service.price_base": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceType(); ok {
		if err := service.PriceTypeValidator(v); err != nil {
			return &ValidationError{Name: "price_type", err: fmt.Errorf(`ent: validator failed for field "Service.price_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := service.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "Service.duration_minutes": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Service.provider"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Service.category"`)
	}
	return nil
}

func (_u *ServiceUpdateOne) sqlSave(ctx context.Context) (_node *Service, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Service.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, service.FieldID)
		for _, f := range fields {
			if !service.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != service.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(service.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(service.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PriceBase(); ok {
		_spec.SetField(service.FieldPriceBase, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceBase(); ok {
		_spec.AddField(service.FieldPriceBase, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceType(); ok {
		_spec.SetField(service.FieldPriceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(service.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(service.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(service.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.ProviderTable,
			Columns: []string{service.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.ProviderTable,
			Columns: []string{service.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.CategoryTable,
			Columns: []string{service.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   service.CategoryTable,
			Columns: []string{service.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Service{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
