// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matheusgosk8/book-me-server/ent/predicate"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCep sets the "cep" field.
func (_u *UserUpdate) SetCep(v string) *UserUpdate {
	_u.mutation.SetCep(v)
	return _u
}

// SetNillableCep sets the "cep" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCep(v *string) *UserUpdate {
	if v != nil {
		_u.SetCep(*v)
	}
	return _u
}

// SetCidade sets the "cidade" field.
func (_u *UserUpdate) SetCidade(v string) *UserUpdate {
	_u.mutation.SetCidade(v)
	return _u
}

// SetNillableCidade sets the "cidade" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCidade(v *string) *UserUpdate {
	if v != nil {
		_u.SetCidade(*v)
	}
	return _u
}

// SetCnpj sets the "cnpj" field.
func (_u *UserUpdate) SetCnpj(v string) *UserUpdate {
	_u.mutation.SetCnpj(v)
	return _u
}

// SetNillableCnpj sets the "cnpj" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCnpj(v *string) *UserUpdate {
	if v != nil {
		_u.SetCnpj(*v)
	}
	return _u
}

// SetConfirmaSenha sets the "confirma_senha" field.
func (_u *UserUpdate) SetConfirmaSenha(v string) *UserUpdate {
	_u.mutation.SetConfirmaSenha(v)
	return _u
}

// SetNillableConfirmaSenha sets the "confirma_senha" field if the given value is not nil.
func (_u *UserUpdate) SetNillableConfirmaSenha(v *string) *UserUpdate {
	if v != nil {
		_u.SetConfirmaSenha(*v)
	}
	return _u
}

// SetCpf sets the "cpf" field.
func (_u *UserUpdate) SetCpf(v string) *UserUpdate {
	_u.mutation.SetCpf(v)
	return _u
}

// SetNillableCpf sets the "cpf" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCpf(v *string) *UserUpdate {
	if v != nil {
		_u.SetCpf(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UserUpdate) SetEstado(v string) *UserUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEstado(v *string) *UserUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetLogradouro sets the "logradouro" field.
func (_u *UserUpdate) SetLogradouro(v string) *UserUpdate {
	_u.mutation.SetLogradouro(v)
	return _u
}

// SetNillableLogradouro sets the "logradouro" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLogradouro(v *string) *UserUpdate {
	if v != nil {
		_u.SetLogradouro(*v)
	}
	return _u
}

// SetNome sets the "nome" field.
func (_u *UserUpdate) SetNome(v string) *UserUpdate {
	_u.mutation.SetNome(v)
	return _u
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNome(v *string) *UserUpdate {
	if v != nil {
		_u.SetNome(*v)
	}
	return _u
}

// SetRua sets the "rua" field.
func (_u *UserUpdate) SetRua(v string) *UserUpdate {
	_u.mutation.SetRua(v)
	return _u
}

// SetNillableRua sets the "rua" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRua(v *string) *UserUpdate {
	if v != nil {
		_u.SetRua(*v)
	}
	return _u
}

// SetSenha sets the "senha" field.
func (_u *UserUpdate) SetSenha(v string) *UserUpdate {
	_u.mutation.SetSenha(v)
	return _u
}

// SetNillableSenha sets the "senha" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSenha(v *string) *UserUpdate {
	if v != nil {
		_u.SetSenha(*v)
	}
	return _u
}

// SetTelefone sets the "telefone" field.
func (_u *UserUpdate) SetTelefone(v string) *UserUpdate {
	_u.mutation.SetTelefone(v)
	return _u
}

// SetNillableTelefone sets the "telefone" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTelefone(v *string) *UserUpdate {
	if v != nil {
		_u.SetTelefone(*v)
	}
	return _u
}

// SetUserType sets the "user_type" field.
func (_u *UserUpdate) SetUserType(v string) *UserUpdate {
	_u.mutation.SetUserType(v)
	return _u
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserType(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserType(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cep(); ok {
		_spec.SetField(user.FieldCep, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cidade(); ok {
		_spec.SetField(user.FieldCidade, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cnpj(); ok {
		_spec.SetField(user.FieldCnpj, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmaSenha(); ok {
		_spec.SetField(user.FieldConfirmaSenha, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cpf(); ok {
		_spec.SetField(user.FieldCpf, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(user.FieldEstado, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logradouro(); ok {
		_spec.SetField(user.FieldLogradouro, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nome(); ok {
		_spec.SetField(user.FieldNome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rua(); ok {
		_spec.SetField(user.FieldRua, field.TypeString, value)
	}
	if value, ok := _u.mutation.Senha(); ok {
		_spec.SetField(user.FieldSenha, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefone(); ok {
		_spec.SetField(user.FieldTelefone, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserType(); ok {
		_spec.SetField(user.FieldUserType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetCep sets the "cep" field.
func (_u *UserUpdateOne) SetCep(v string) *UserUpdateOne {
	_u.mutation.SetCep(v)
	return _u
}

// SetNillableCep sets the "cep" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCep(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCep(*v)
	}
	return _u
}

// SetCidade sets the "cidade" field.
func (_u *UserUpdateOne) SetCidade(v string) *UserUpdateOne {
	_u.mutation.SetCidade(v)
	return _u
}

// SetNillableCidade sets the "cidade" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCidade(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCidade(*v)
	}
	return _u
}

// SetCnpj sets the "cnpj" field.
func (_u *UserUpdateOne) SetCnpj(v string) *UserUpdateOne {
	_u.mutation.SetCnpj(v)
	return _u
}

// SetNillableCnpj sets the "cnpj" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCnpj(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCnpj(*v)
	}
	return _u
}

// SetConfirmaSenha sets the "confirma_senha" field.
func (_u *UserUpdateOne) SetConfirmaSenha(v string) *UserUpdateOne {
	_u.mutation.SetConfirmaSenha(v)
	return _u
}

// SetNillableConfirmaSenha sets the "confirma_senha" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableConfirmaSenha(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetConfirmaSenha(*v)
	}
	return _u
}

// SetCpf sets the "cpf" field.
func (_u *UserUpdateOne) SetCpf(v string) *UserUpdateOne {
	_u.mutation.SetCpf(v)
	return _u
}

// SetNillableCpf sets the "cpf" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCpf(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCpf(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *UserUpdateOne) SetEstado(v string) *UserUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEstado(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetLogradouro sets the "logradouro" field.
func (_u *UserUpdateOne) SetLogradouro(v string) *UserUpdateOne {
	_u.mutation.SetLogradouro(v)
	return _u
}

// SetNillableLogradouro sets the "logradouro" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLogradouro(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLogradouro(*v)
	}
	return _u
}

// SetNome sets the "nome" field.
func (_u *UserUpdateOne) SetNome(v string) *UserUpdateOne {
	_u.mutation.SetNome(v)
	return _u
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNome(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNome(*v)
	}
	return _u
}

// SetRua sets the "rua" field.
func (_u *UserUpdateOne) SetRua(v string) *UserUpdateOne {
	_u.mutation.SetRua(v)
	return _u
}

// SetNillableRua sets the "rua" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRua(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRua(*v)
	}
	return _u
}

// SetSenha sets the "senha" field.
func (_u *UserUpdateOne) SetSenha(v string) *UserUpdateOne {
	_u.mutation.SetSenha(v)
	return _u
}

// SetNillableSenha sets the "senha" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSenha(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSenha(*v)
	}
	return _u
}

// SetTelefone sets the "telefone" field.
func (_u *UserUpdateOne) SetTelefone(v string) *UserUpdateOne {
	_u.mutation.SetTelefone(v)
	return _u
}

// SetNillableTelefone sets the "telefone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTelefone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTelefone(*v)
	}
	return _u
}

// SetUserType sets the "user_type" field.
func (_u *UserUpdateOne) SetUserType(v string) *UserUpdateOne {
	_u.mutation.SetUserType(v)
	return _u
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserType(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserType(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cep(); ok {
		_spec.SetField(user.FieldCep, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cidade(); ok {
		_spec.SetField(user.FieldCidade, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cnpj(); ok {
		_spec.SetField(user.FieldCnpj, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmaSenha(); ok {
		_spec.SetField(user.FieldConfirmaSenha, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cpf(); ok {
		_spec.SetField(user.FieldCpf, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(user.FieldEstado, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logradouro(); ok {
		_spec.SetField(user.FieldLogradouro, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nome(); ok {
		_spec.SetField(user.FieldNome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rua(); ok {
		_spec.SetField(user.FieldRua, field.TypeString, value)
	}
	if value, ok := _u.mutation.Senha(); ok {
		_spec.SetField(user.FieldSenha, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefone(); ok {
		_spec.SetField(user.FieldTelefone, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserType(); ok {
		_spec.SetField(user.FieldUserType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
