// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/address"
	"github.com/matheusgosk8/book-me-server/ent/order"
	"github.com/matheusgosk8/book-me-server/ent/proposal"
	"github.com/matheusgosk8/book-me-server/ent/providerprofile"
	"github.com/matheusgosk8/book-me-server/ent/review"
	"github.com/matheusgosk8/book-me-server/ent/service"
	"github.com/matheusgosk8/book-me-server/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetCep sets the "cep" field.
func (_c *UserCreate) SetCep(v string) *UserCreate {
	_c.mutation.SetCep(v)
	return _c
}

// SetCidade sets the "cidade" field.
func (_c *UserCreate) SetCidade(v string) *UserCreate {
	_c.mutation.SetCidade(v)
	return _c
}

// SetCnpj sets the "cnpj" field.
func (_c *UserCreate) SetCnpj(v string) *UserCreate {
	_c.mutation.SetCnpj(v)
	return _c
}

// SetConfirmaSenha sets the "confirma_senha" field.
func (_c *UserCreate) SetConfirmaSenha(v string) *UserCreate {
	_c.mutation.SetConfirmaSenha(v)
	return _c
}

// SetCpf sets the "cpf" field.
func (_c *UserCreate) SetCpf(v string) *UserCreate {
	_c.mutation.SetCpf(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetEstado sets the "estado" field.
func (_c *UserCreate) SetEstado(v string) *UserCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetLogradouro sets the "logradouro" field.
func (_c *UserCreate) SetLogradouro(v string) *UserCreate {
	_c.mutation.SetLogradouro(v)
	return _c
}

// SetNome sets the "nome" field.
func (_c *UserCreate) SetNome(v string) *UserCreate {
	_c.mutation.SetNome(v)
	return _c
}

// SetRua sets the "rua" field.
func (_c *UserCreate) SetRua(v string) *UserCreate {
	_c.mutation.SetRua(v)
	return _c
}

// SetSenha sets the "senha" field.
func (_c *UserCreate) SetSenha(v string) *UserCreate {
	_c.mutation.SetSenha(v)
	return _c
}

// SetTelefone sets the "telefone" field.
func (_c *UserCreate) SetTelefone(v string) *UserCreate {
	_c.mutation.SetTelefone(v)
	return _c
}

// SetUserType sets the "user_type" field.
func (_c *UserCreate) SetUserType(v string) *UserCreate {
	_c.mutation.SetUserType(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v uuid.UUID) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserCreate) SetNillableID(v *uuid.UUID) *UserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProviderProfileID sets the "provider_profile" edge to the ProviderProfile entity by ID.
func (_c *UserCreate) SetProviderProfileID(id uuid.UUID) *UserCreate {
	_c.mutation.SetProviderProfileID(id)
	return _c
}

// SetNillableProviderProfileID sets the "provider_profile" edge to the ProviderProfile entity by ID if the given value is not nil.
func (_c *UserCreate) SetNillableProviderProfileID(id *uuid.UUID) *UserCreate {
	if id != nil {
		_c = _c.SetProviderProfileID(*id)
	}
	return _c
}

// SetProviderProfile sets the "provider_profile" edge to the ProviderProfile entity.
func (_c *UserCreate) SetProviderProfile(v *ProviderProfile) *UserCreate {
	return _c.SetProviderProfileID(v.ID)
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (_c *UserCreate) AddAddressIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddAddressIDs(ids...)
	return _c
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (_c *UserCreate) AddAddresses(v ...*Address) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAddressIDs(ids...)
}

// AddOrdersCreatedIDs adds the "orders_created" edge to the Order entity by IDs.
func (_c *UserCreate) AddOrdersCreatedIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddOrdersCreatedIDs(ids...)
	return _c
}

// AddOrdersCreated adds the "orders_created" edges to the Order entity.
func (_c *UserCreate) AddOrdersCreated(v ...*Order) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrdersCreatedIDs(ids...)
}

// AddOrdersFulfilledIDs adds the "orders_fulfilled" edge to the Order entity by IDs.
func (_c *UserCreate) AddOrdersFulfilledIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddOrdersFulfilledIDs(ids...)
	return _c
}

// AddOrdersFulfilled adds the "orders_fulfilled" edges to the Order entity.
func (_c *UserCreate) AddOrdersFulfilled(v ...*Order) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrdersFulfilledIDs(ids...)
}

// AddProposalsSentIDs adds the "proposals_sent" edge to the Proposal entity by IDs.
func (_c *UserCreate) AddProposalsSentIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddProposalsSentIDs(ids...)
	return _c
}

// AddProposalsSent adds the "proposals_sent" edges to the Proposal entity.
func (_c *UserCreate) AddProposalsSent(v ...*Proposal) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProposalsSentIDs(ids...)
}

// AddReviewsWrittenIDs adds the "reviews_written" edge to the Review entity by IDs.
func (_c *UserCreate) AddReviewsWrittenIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddReviewsWrittenIDs(ids...)
	return _c
}

// AddReviewsWritten adds the "reviews_written" edges to the Review entity.
func (_c *UserCreate) AddReviewsWritten(v ...*Review) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewsWrittenIDs(ids...)
}

// AddReviewsReceivedIDs adds the "reviews_received" edge to the Review entity by IDs.
func (_c *UserCreate) AddReviewsReceivedIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddReviewsReceivedIDs(ids...)
	return _c
}

// AddReviewsReceived adds the "reviews_received" edges to the Review entity.
func (_c *UserCreate) AddReviewsReceived(v ...*Review) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReviewsReceivedIDs(ids...)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (_c *UserCreate) AddServiceIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddServiceIDs(ids...)
	return _c
}

// AddServices adds the "services" edges to the Service entity.
func (_c *UserCreate) AddServices(v ...*Service) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddServiceIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := user.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Cep(); !ok {
		return &ValidationError{Name: "cep", err: errors.New(`ent: missing required field "User.cep"`)}
	}
	if _, ok := _c.mutation.Cidade(); !ok {
		return &ValidationError{Name: "cidade", err: errors.New(`ent: missing required field "User.cidade"`)}
	}
	if _, ok := _c.mutation.Cnpj(); !ok {
		return &ValidationError{Name: "cnpj", err: errors.New(`ent: missing required field "User.cnpj"`)}
	}
	if _, ok := _c.mutation.ConfirmaSenha(); !ok {
		return &ValidationError{Name: "confirma_senha", err: errors.New(`ent: missing required field "User.confirma_senha"`)}
	}
	if _, ok := _c.mutation.Cpf(); !ok {
		return &ValidationError{Name: "cpf", err: errors.New(`ent: missing required field "User.cpf"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "User.estado"`)}
	}
	if _, ok := _c.mutation.Logradouro(); !ok {
		return &ValidationError{Name: "logradouro", err: errors.New(`ent: missing required field "User.logradouro"`)}
	}
	if _, ok := _c.mutation.Nome(); !ok {
		return &ValidationError{Name: "nome", err: errors.New(`ent: missing required field "User.nome"`)}
	}
	if _, ok := _c.mutation.Rua(); !ok {
		return &ValidationError{Name: "rua", err: errors.New(`ent: missing required field "User.rua"`)}
	}
	if _, ok := _c.mutation.Senha(); !ok {
		return &ValidationError{Name: "senha", err: errors.New(`ent: missing required field "User.senha"`)}
	}
	if _, ok := _c.mutation.Telefone(); !ok {
		return &ValidationError{Name: "telefone", err: errors.New(`ent: missing required field "User.telefone"`)}
	}
	if _, ok := _c.mutation.UserType(); !ok {
		return &ValidationError{Name: "user_type", err: errors.New(`ent: missing required field "User.user_type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Cep(); ok {
		_spec.SetField(user.FieldCep, field.TypeString, value)
		_node.Cep = value
	}
	if value, ok := _c.mutation.Cidade(); ok {
		_spec.SetField(user.FieldCidade, field.TypeString, value)
		_node.Cidade = value
	}
	if value, ok := _c.mutation.Cnpj(); ok {
		_spec.SetField(user.FieldCnpj, field.TypeString, value)
		_node.Cnpj = value
	}
	if value, ok := _c.mutation.ConfirmaSenha(); ok {
		_spec.SetField(user.FieldConfirmaSenha, field.TypeString, value)
		_node.ConfirmaSenha = value
	}
	if value, ok := _c.mutation.Cpf(); ok {
		_spec.SetField(user.FieldCpf, field.TypeString, value)
		_node.Cpf = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(user.FieldEstado, field.TypeString, value)
		_node.Estado = value
	}
	if value, ok := _c.mutation.Logradouro(); ok {
		_spec.SetField(user.FieldLogradouro, field.TypeString, value)
		_node.Logradouro = value
	}
	if value, ok := _c.mutation.Nome(); ok {
		_spec.SetField(user.FieldNome, field.TypeString, value)
		_node.Nome = value
	}
	if value, ok := _c.mutation.Rua(); ok {
		_spec.SetField(user.FieldRua, field.TypeString, value)
		_node.Rua = value
	}
	if value, ok := _c.mutation.Senha(); ok {
		_spec.SetField(user.FieldSenha, field.TypeString, value)
		_node.Senha = value
	}
	if value, ok := _c.mutation.Telefone(); ok {
		_spec.SetField(user.FieldTelefone, field.TypeString, value)
		_node.Telefone = value
	}
	if value, ok := _c.mutation.UserType(); ok {
		_spec.SetField(user.FieldUserType, field.TypeString, value)
		_node.UserType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProviderProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ProviderProfileTable,
			Columns: []string{user.ProviderProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(providerprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AddressesTable,
			Columns: []string{user.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersCreatedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrdersCreatedTable,
			Columns: []string{user.OrdersCreatedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrdersFulfilledIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrdersFulfilledTable,
			Columns: []string{user.OrdersFulfilledColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProposalsSentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProposalsSentTable,
			Columns: []string{user.ProposalsSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proposal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewsWrittenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsWrittenTable,
			Columns: []string{user.ReviewsWrittenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReviewsReceivedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsReceivedTable,
			Columns: []string{user.ReviewsReceivedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ServicesTable,
			Columns: []string{user.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
