// Code generated by ent, DO NOT EDIT.

package service

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the service type in the database.
	Label = "service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPriceBase holds the string denoting the price_base field in the database.
	FieldPriceBase = "price_base"
	// FieldPriceType holds the string denoting the price_type field in the database.
	FieldPriceType = "price_type"
	// FieldDurationMinutes holds the string denoting the duration_minutes field in the database.
	FieldDurationMinutes = "duration_minutes"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// Table holds the table name of the service in the database.
	Table = "services"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "services"
	// ProviderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProviderInverseTable = "users"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "user_services"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "services"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_services"
)

// Columns holds all SQL columns for service fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldPriceBase,
	FieldPriceType,
	FieldDurationMinutes,
	FieldIsActive,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "services"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"category_services",
	"user_services",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// PriceBaseValidator is a validator for the "price_base" field. It is called by the builders before save.
	PriceBaseValidator func(float64) error
	// DurationMinutesValidator is a validator for the "duration_minutes" field. It is called by the builders before save.
	DurationMinutesValidator func(int) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PriceType defines the type for the "price_type" enum field.
type PriceType string

// PriceTypeFixed is the default value of the PriceType enum.
const DefaultPriceType = PriceTypeFixed

// PriceType values.
const (
	PriceTypeFixed  PriceType = "fixed"
	PriceTypeHourly PriceType = "hourly"
)

func (pt PriceType) String() string {
	return string(pt)
}

// PriceTypeValidator is a validator for the "price_type" field enum values. It is called by the builders before save.
func PriceTypeValidator(pt PriceType) error {
	switch pt {
	case PriceTypeFixed, PriceTypeHourly:
		return nil
	default:
		return fmt.Errorf("service: invalid enum value for price_type field: %q", pt)
	}
}

// OrderOption defines the ordering options for the Service queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPriceBase orders the results by the price_base field.
func ByPriceBase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceBase, opts...).ToFunc()
}

// ByPriceType orders the results by the price_type field.
func ByPriceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceType, opts...).ToFunc()
}

// ByDurationMinutes orders the results by the duration_minutes field.
func ByDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMinutes, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
