// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/matheusgosk8/book-me-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Cep applies equality check predicate on the "cep" field. It's identical to CepEQ.
func Cep(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCep, v))
}

// Cidade applies equality check predicate on the "cidade" field. It's identical to CidadeEQ.
func Cidade(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCidade, v))
}

// Cnpj applies equality check predicate on the "cnpj" field. It's identical to CnpjEQ.
func Cnpj(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCnpj, v))
}

// ConfirmaSenha applies equality check predicate on the "confirma_senha" field. It's identical to ConfirmaSenhaEQ.
func ConfirmaSenha(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldConfirmaSenha, v))
}

// Cpf applies equality check predicate on the "cpf" field. It's identical to CpfEQ.
func Cpf(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCpf, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Estado applies equality check predicate on the "estado" field. It's identical to EstadoEQ.
func Estado(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEstado, v))
}

// Logradouro applies equality check predicate on the "logradouro" field. It's identical to LogradouroEQ.
func Logradouro(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogradouro, v))
}

// Nome applies equality check predicate on the "nome" field. It's identical to NomeEQ.
func Nome(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNome, v))
}

// Rua applies equality check predicate on the "rua" field. It's identical to RuaEQ.
func Rua(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRua, v))
}

// Senha applies equality check predicate on the "senha" field. It's identical to SenhaEQ.
func Senha(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSenha, v))
}

// Telefone applies equality check predicate on the "telefone" field. It's identical to TelefoneEQ.
func Telefone(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTelefone, v))
}

// UserType applies equality check predicate on the "user_type" field. It's identical to UserTypeEQ.
func UserType(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// CepEQ applies the EQ predicate on the "cep" field.
func CepEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCep, v))
}

// CepNEQ applies the NEQ predicate on the "cep" field.
func CepNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCep, v))
}

// CepIn applies the In predicate on the "cep" field.
func CepIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldCep, vs...))
}

// CepNotIn applies the NotIn predicate on the "cep" field.
func CepNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCep, vs...))
}

// CepGT applies the GT predicate on the "cep" field.
func CepGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldCep, v))
}

// CepGTE applies the GTE predicate on the "cep" field.
func CepGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCep, v))
}

// CepLT applies the LT predicate on the "cep" field.
func CepLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldCep, v))
}

// CepLTE applies the LTE predicate on the "cep" field.
func CepLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCep, v))
}

// CepContains applies the Contains predicate on the "cep" field.
func CepContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldCep, v))
}

// CepHasPrefix applies the HasPrefix predicate on the "cep" field.
func CepHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldCep, v))
}

// CepHasSuffix applies the HasSuffix predicate on the "cep" field.
func CepHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldCep, v))
}

// CepEqualFold applies the EqualFold predicate on the "cep" field.
func CepEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldCep, v))
}

// CepContainsFold applies the ContainsFold predicate on the "cep" field.
func CepContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldCep, v))
}

// CidadeEQ applies the EQ predicate on the "cidade" field.
func CidadeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCidade, v))
}

// CidadeNEQ applies the NEQ predicate on the "cidade" field.
func CidadeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCidade, v))
}

// CidadeIn applies the In predicate on the "cidade" field.
func CidadeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldCidade, vs...))
}

// CidadeNotIn applies the NotIn predicate on the "cidade" field.
func CidadeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCidade, vs...))
}

// CidadeGT applies the GT predicate on the "cidade" field.
func CidadeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldCidade, v))
}

// CidadeGTE applies the GTE predicate on the "cidade" field.
func CidadeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCidade, v))
}

// CidadeLT applies the LT predicate on the "cidade" field.
func CidadeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldCidade, v))
}

// CidadeLTE applies the LTE predicate on the "cidade" field.
func CidadeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCidade, v))
}

// CidadeContains applies the Contains predicate on the "cidade" field.
func CidadeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldCidade, v))
}

// CidadeHasPrefix applies the HasPrefix predicate on the "cidade" field.
func CidadeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldCidade, v))
}

// CidadeHasSuffix applies the HasSuffix predicate on the "cidade" field.
func CidadeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldCidade, v))
}

// CidadeEqualFold applies the EqualFold predicate on the "cidade" field.
func CidadeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldCidade, v))
}

// CidadeContainsFold applies the ContainsFold predicate on the "cidade" field.
func CidadeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldCidade, v))
}

// CnpjEQ applies the EQ predicate on the "cnpj" field.
func CnpjEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCnpj, v))
}

// CnpjNEQ applies the NEQ predicate on the "cnpj" field.
func CnpjNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCnpj, v))
}

// CnpjIn applies the In predicate on the "cnpj" field.
func CnpjIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldCnpj, vs...))
}

// CnpjNotIn applies the NotIn predicate on the "cnpj" field.
func CnpjNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCnpj, vs...))
}

// CnpjGT applies the GT predicate on the "cnpj" field.
func CnpjGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldCnpj, v))
}

// CnpjGTE applies the GTE predicate on the "cnpj" field.
func CnpjGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCnpj, v))
}

// CnpjLT applies the LT predicate on the "cnpj" field.
func CnpjLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldCnpj, v))
}

// CnpjLTE applies the LTE predicate on the "cnpj" field.
func CnpjLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCnpj, v))
}

// CnpjContains applies the Contains predicate on the "cnpj" field.
func CnpjContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldCnpj, v))
}

// CnpjHasPrefix applies the HasPrefix predicate on the "cnpj" field.
func CnpjHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldCnpj, v))
}

// CnpjHasSuffix applies the HasSuffix predicate on the "cnpj" field.
func CnpjHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldCnpj, v))
}

// CnpjEqualFold applies the EqualFold predicate on the "cnpj" field.
func CnpjEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldCnpj, v))
}

// CnpjContainsFold applies the ContainsFold predicate on the "cnpj" field.
func CnpjContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldCnpj, v))
}

// ConfirmaSenhaEQ applies the EQ predicate on the "confirma_senha" field.
func ConfirmaSenhaEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldConfirmaSenha, v))
}

// ConfirmaSenhaNEQ applies the NEQ predicate on the "confirma_senha" field.
func ConfirmaSenhaNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldConfirmaSenha, v))
}

// ConfirmaSenhaIn applies the In predicate on the "confirma_senha" field.
func ConfirmaSenhaIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldConfirmaSenha, vs...))
}

// ConfirmaSenhaNotIn applies the NotIn predicate on the "confirma_senha" field.
func ConfirmaSenhaNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldConfirmaSenha, vs...))
}

// ConfirmaSenhaGT applies the GT predicate on the "confirma_senha" field.
func ConfirmaSenhaGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldConfirmaSenha, v))
}

// ConfirmaSenhaGTE applies the GTE predicate on the "confirma_senha" field.
func ConfirmaSenhaGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldConfirmaSenha, v))
}

// ConfirmaSenhaLT applies the LT predicate on the "confirma_senha" field.
func ConfirmaSenhaLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldConfirmaSenha, v))
}

// ConfirmaSenhaLTE applies the LTE predicate on the "confirma_senha" field.
func ConfirmaSenhaLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldConfirmaSenha, v))
}

// ConfirmaSenhaContains applies the Contains predicate on the "confirma_senha" field.
func ConfirmaSenhaContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldConfirmaSenha, v))
}

// ConfirmaSenhaHasPrefix applies the HasPrefix predicate on the "confirma_senha" field.
func ConfirmaSenhaHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldConfirmaSenha, v))
}

// ConfirmaSenhaHasSuffix applies the HasSuffix predicate on the "confirma_senha" field.
func ConfirmaSenhaHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldConfirmaSenha, v))
}

// ConfirmaSenhaEqualFold applies the EqualFold predicate on the "confirma_senha" field.
func ConfirmaSenhaEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldConfirmaSenha, v))
}

// ConfirmaSenhaContainsFold applies the ContainsFold predicate on the "confirma_senha" field.
func ConfirmaSenhaContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldConfirmaSenha, v))
}

// CpfEQ applies the EQ predicate on the "cpf" field.
func CpfEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCpf, v))
}

// CpfNEQ applies the NEQ predicate on the "cpf" field.
func CpfNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCpf, v))
}

// CpfIn applies the In predicate on the "cpf" field.
func CpfIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldCpf, vs...))
}

// CpfNotIn applies the NotIn predicate on the "cpf" field.
func CpfNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCpf, vs...))
}

// CpfGT applies the GT predicate on the "cpf" field.
func CpfGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldCpf, v))
}

// CpfGTE applies the GTE predicate on the "cpf" field.
func CpfGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCpf, v))
}

// CpfLT applies the LT predicate on the "cpf" field.
func CpfLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldCpf, v))
}

// CpfLTE applies the LTE predicate on the "cpf" field.
func CpfLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCpf, v))
}

// CpfContains applies the Contains predicate on the "cpf" field.
func CpfContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldCpf, v))
}

// CpfHasPrefix applies the HasPrefix predicate on the "cpf" field.
func CpfHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldCpf, v))
}

// CpfHasSuffix applies the HasSuffix predicate on the "cpf" field.
func CpfHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldCpf, v))
}

// CpfEqualFold applies the EqualFold predicate on the "cpf" field.
func CpfEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldCpf, v))
}

// CpfContainsFold applies the ContainsFold predicate on the "cpf" field.
func CpfContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldCpf, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// EstadoEQ applies the EQ predicate on the "estado" field.
func EstadoEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEstado, v))
}

// EstadoNEQ applies the NEQ predicate on the "estado" field.
func EstadoNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEstado, v))
}

// EstadoIn applies the In predicate on the "estado" field.
func EstadoIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEstado, vs...))
}

// EstadoNotIn applies the NotIn predicate on the "estado" field.
func EstadoNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEstado, vs...))
}

// EstadoGT applies the GT predicate on the "estado" field.
func EstadoGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEstado, v))
}

// EstadoGTE applies the GTE predicate on the "estado" field.
func EstadoGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEstado, v))
}

// EstadoLT applies the LT predicate on the "estado" field.
func EstadoLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEstado, v))
}

// EstadoLTE applies the LTE predicate on the "estado" field.
func EstadoLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEstado, v))
}

// EstadoContains applies the Contains predicate on the "estado" field.
func EstadoContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEstado, v))
}

// EstadoHasPrefix applies the HasPrefix predicate on the "estado" field.
func EstadoHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEstado, v))
}

// EstadoHasSuffix applies the HasSuffix predicate on the "estado" field.
func EstadoHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEstado, v))
}

// EstadoEqualFold applies the EqualFold predicate on the "estado" field.
func EstadoEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEstado, v))
}

// EstadoContainsFold applies the ContainsFold predicate on the "estado" field.
func EstadoContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEstado, v))
}

// LogradouroEQ applies the EQ predicate on the "logradouro" field.
func LogradouroEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogradouro, v))
}

// LogradouroNEQ applies the NEQ predicate on the "logradouro" field.
func LogradouroNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLogradouro, v))
}

// LogradouroIn applies the In predicate on the "logradouro" field.
func LogradouroIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLogradouro, vs...))
}

// LogradouroNotIn applies the NotIn predicate on the "logradouro" field.
func LogradouroNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLogradouro, vs...))
}

// LogradouroGT applies the GT predicate on the "logradouro" field.
func LogradouroGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLogradouro, v))
}

// LogradouroGTE applies the GTE predicate on the "logradouro" field.
func LogradouroGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLogradouro, v))
}

// LogradouroLT applies the LT predicate on the "logradouro" field.
func LogradouroLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLogradouro, v))
}

// LogradouroLTE applies the LTE predicate on the "logradouro" field.
func LogradouroLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLogradouro, v))
}

// LogradouroContains applies the Contains predicate on the "logradouro" field.
func LogradouroContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLogradouro, v))
}

// LogradouroHasPrefix applies the HasPrefix predicate on the "logradouro" field.
func LogradouroHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLogradouro, v))
}

// LogradouroHasSuffix applies the HasSuffix predicate on the "logradouro" field.
func LogradouroHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLogradouro, v))
}

// LogradouroEqualFold applies the EqualFold predicate on the "logradouro" field.
func LogradouroEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLogradouro, v))
}

// LogradouroContainsFold applies the ContainsFold predicate on the "logradouro" field.
func LogradouroContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLogradouro, v))
}

// NomeEQ applies the EQ predicate on the "nome" field.
func NomeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldNome, v))
}

// NomeNEQ applies the NEQ predicate on the "nome" field.
func NomeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldNome, v))
}

// NomeIn applies the In predicate on the "nome" field.
func NomeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldNome, vs...))
}

// NomeNotIn applies the NotIn predicate on the "nome" field.
func NomeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldNome, vs...))
}

// NomeGT applies the GT predicate on the "nome" field.
func NomeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldNome, v))
}

// NomeGTE applies the GTE predicate on the "nome" field.
func NomeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldNome, v))
}

// NomeLT applies the LT predicate on the "nome" field.
func NomeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldNome, v))
}

// NomeLTE applies the LTE predicate on the "nome" field.
func NomeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldNome, v))
}

// NomeContains applies the Contains predicate on the "nome" field.
func NomeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldNome, v))
}

// NomeHasPrefix applies the HasPrefix predicate on the "nome" field.
func NomeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldNome, v))
}

// NomeHasSuffix applies the HasSuffix predicate on the "nome" field.
func NomeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldNome, v))
}

// NomeEqualFold applies the EqualFold predicate on the "nome" field.
func NomeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldNome, v))
}

// NomeContainsFold applies the ContainsFold predicate on the "nome" field.
func NomeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldNome, v))
}

// RuaEQ applies the EQ predicate on the "rua" field.
func RuaEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRua, v))
}

// RuaNEQ applies the NEQ predicate on the "rua" field.
func RuaNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRua, v))
}

// RuaIn applies the In predicate on the "rua" field.
func RuaIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRua, vs...))
}

// RuaNotIn applies the NotIn predicate on the "rua" field.
func RuaNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRua, vs...))
}

// RuaGT applies the GT predicate on the "rua" field.
func RuaGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRua, v))
}

// RuaGTE applies the GTE predicate on the "rua" field.
func RuaGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRua, v))
}

// RuaLT applies the LT predicate on the "rua" field.
func RuaLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRua, v))
}

// RuaLTE applies the LTE predicate on the "rua" field.
func RuaLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRua, v))
}

// RuaContains applies the Contains predicate on the "rua" field.
func RuaContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRua, v))
}

// RuaHasPrefix applies the HasPrefix predicate on the "rua" field.
func RuaHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRua, v))
}

// RuaHasSuffix applies the HasSuffix predicate on the "rua" field.
func RuaHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRua, v))
}

// RuaEqualFold applies the EqualFold predicate on the "rua" field.
func RuaEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRua, v))
}

// RuaContainsFold applies the ContainsFold predicate on the "rua" field.
func RuaContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRua, v))
}

// SenhaEQ applies the EQ predicate on the "senha" field.
func SenhaEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSenha, v))
}

// SenhaNEQ applies the NEQ predicate on the "senha" field.
func SenhaNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSenha, v))
}

// SenhaIn applies the In predicate on the "senha" field.
func SenhaIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSenha, vs...))
}

// SenhaNotIn applies the NotIn predicate on the "senha" field.
func SenhaNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSenha, vs...))
}

// SenhaGT applies the GT predicate on the "senha" field.
func SenhaGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSenha, v))
}

// SenhaGTE applies the GTE predicate on the "senha" field.
func SenhaGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSenha, v))
}

// SenhaLT applies the LT predicate on the "senha" field.
func SenhaLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSenha, v))
}

// SenhaLTE applies the LTE predicate on the "senha" field.
func SenhaLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSenha, v))
}

// SenhaContains applies the Contains predicate on the "senha" field.
func SenhaContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSenha, v))
}

// SenhaHasPrefix applies the HasPrefix predicate on the "senha" field.
func SenhaHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSenha, v))
}

// SenhaHasSuffix applies the HasSuffix predicate on the "senha" field.
func SenhaHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSenha, v))
}

// SenhaEqualFold applies the EqualFold predicate on the "senha" field.
func SenhaEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSenha, v))
}

// SenhaContainsFold applies the ContainsFold predicate on the "senha" field.
func SenhaContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSenha, v))
}

// TelefoneEQ applies the EQ predicate on the "telefone" field.
func TelefoneEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTelefone, v))
}

// TelefoneNEQ applies the NEQ predicate on the "telefone" field.
func TelefoneNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTelefone, v))
}

// TelefoneIn applies the In predicate on the "telefone" field.
func TelefoneIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTelefone, vs...))
}

// TelefoneNotIn applies the NotIn predicate on the "telefone" field.
func TelefoneNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTelefone, vs...))
}

// TelefoneGT applies the GT predicate on the "telefone" field.
func TelefoneGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTelefone, v))
}

// TelefoneGTE applies the GTE predicate on the "telefone" field.
func TelefoneGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTelefone, v))
}

// TelefoneLT applies the LT predicate on the "telefone" field.
func TelefoneLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTelefone, v))
}

// TelefoneLTE applies the LTE predicate on the "telefone" field.
func TelefoneLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTelefone, v))
}

// TelefoneContains applies the Contains predicate on the "telefone" field.
func TelefoneContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTelefone, v))
}

// TelefoneHasPrefix applies the HasPrefix predicate on the "telefone" field.
func TelefoneHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTelefone, v))
}

// TelefoneHasSuffix applies the HasSuffix predicate on the "telefone" field.
func TelefoneHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTelefone, v))
}

// TelefoneEqualFold applies the EqualFold predicate on the "telefone" field.
func TelefoneEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTelefone, v))
}

// TelefoneContainsFold applies the ContainsFold predicate on the "telefone" field.
func TelefoneContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTelefone, v))
}

// UserTypeEQ applies the EQ predicate on the "user_type" field.
func UserTypeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserType, v))
}

// UserTypeNEQ applies the NEQ predicate on the "user_type" field.
func UserTypeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserType, v))
}

// UserTypeIn applies the In predicate on the "user_type" field.
func UserTypeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserType, vs...))
}

// UserTypeNotIn applies the NotIn predicate on the "user_type" field.
func UserTypeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserType, vs...))
}

// UserTypeGT applies the GT predicate on the "user_type" field.
func UserTypeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserType, v))
}

// UserTypeGTE applies the GTE predicate on the "user_type" field.
func UserTypeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserType, v))
}

// UserTypeLT applies the LT predicate on the "user_type" field.
func UserTypeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserType, v))
}

// UserTypeLTE applies the LTE predicate on the "user_type" field.
func UserTypeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserType, v))
}

// UserTypeContains applies the Contains predicate on the "user_type" field.
func UserTypeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserType, v))
}

// UserTypeHasPrefix applies the HasPrefix predicate on the "user_type" field.
func UserTypeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserType, v))
}

// UserTypeHasSuffix applies the HasSuffix predicate on the "user_type" field.
func UserTypeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserType, v))
}

// UserTypeEqualFold applies the EqualFold predicate on the "user_type" field.
func UserTypeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserType, v))
}

// UserTypeContainsFold applies the ContainsFold predicate on the "user_type" field.
func UserTypeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
