name: Go CI

on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: book-me-be
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Generate ent code
        run: go run entgo.io/ent/cmd/ent generate ./ent/schema

      - name: Build project (ensure generated code compiles)
        run: go build ./...

      - name: Run Unit Tests
        run: make test-unit

      - name: Run DB migrations and seed
        env:
          DATABASE_URL: postgres://postgres:docker@localhost:5433/book-me-be?sslmode=disable
        run: |
          # aguarda o Postgres ficar pronto
          until pg_isready -h localhost -p 5433; do sleep 1; done
          go run ./cmd/migrate

      - name: Run E2E Tests
        env:
          DATABASE_URL: postgres://postgres:docker@localhost:5433/book-me-be?sslmode=disable
        run: make test-e2e
